### ISSUE TITLE
Loving the github update feature!

### ISSUE THREAD

**Issue by FlaMike** [rstrouse/ESPSomfy-RTS#213]
Just wanted to give you a shout out "Thank you!" for adding this feature.  It really simplifies & streamlines updating the programs!  I used it for the first time over the weekend to update to 2.2.  EZ PZ!   I also appreciate showing the version installed on the device's home page.  Nice touches all!

Thanks again for creating and sharing this superb project!  It's an excellent convenience & addition to our home.

**Comment by rstrouse** [comment]
If you are paying attention it also has a firmware updater from HA.  This is because I must either be a masochist or I simply need to know the answer to what if.

**Comment by FlaMike** [comment]
You are just too to we who enjoy the fruits of your labor!!!  Thanks!  Just installed 2.3 from HA.  So sweet!!!

**Comment by paede81** [comment]
Can the git hub updater be used for all esp devices (esp, esp-s2, esp-s3, esp-c3)?

**Comment by rstrouse** [comment]
So far yes.

**Comment by rstrouse** [comment]
I got around to testing more thoroughly as I only had one sample of a non-WROOM device.  So after v2.2.4 the github updater works reliably with esp32, esp32-s2, esp32-s3, and esp32-c3.   As it turns out that while it initially appeared to update from prior versions it was just updating the littlefs partition.
