### ISSUE TITLE
Downgrade -> Restore no response

### ISSUE THREAD

**Issue by xxLexanixx** [rstrouse/ESPSomfy-RTS#229]
After Firmware Update from 2.2.4 to 2.3.0 had i no response from the ESP, no Shutter or Webinterface.
so I reinstalled firmware 2.2.4 and restored the backup.
After the restoration, the roller blinds no longer work correctly.
In the web interface no one responds to up or down commands anymore.
When I re-add the blinds the problem is the same

the remote controls respond when I scan the frequency.
But as soon as I want to pair it, nothing responds

**Comment by rstrouse** [comment]
When you flashed the firmware to 2.3.0 there was an interruption on the download stream for the filesystem.  For me I had a lot of trouble getting that to happen but have since added some additional checks so it does not immediately bail on the download of the web files.   Unfortunately, this part of the process cannot be rolled back on the ESP32 at the moment.  The firmware if it completes is always fine since that process will roll back and not attempt to pull the filesystem from Github.

Please update to 2.3.0 and then lets focus on the lack of response from the motors.   Essentially, there are only a couple of things that can make this happen and these are it.

1. The wire between the pin assigned as TX in the configuration is not getting contact to the pin assigned to GDO0 on the transceiver.  This can happen if you are using Dupont connections as each time the connector is connected it loosens a little with many of the cheap connectors out there.

2. The backup file restored was not the most recent one and the shade addresses/rolling codes are not correct.

When you say you re-added the blinds what do you mean?  Did you unpair them successfully with the motor or did you just delete them and add them back in?

**Comment by xxLexanixx** [comment]
After restoring from the backup, I deleted them all and had to assign new numbers, then everything worked again.
However, no one responded with the “old” numbers.

**Comment by rstrouse** [comment]
Weird.  I am going to close this for now but it does seem like the rolling codes may have been overwritten by something.  These are stored in the NVS so they should not have been overwritten unless a completely different firmware that repartitions the nvs was installed.
