### ISSUE TITLE
Question: group delay

### ISSUE THREAD

**Issue by AlexOwl** [rstrouse/ESPSomfy-RTS#97]
Is it possible to change or minimize the delay between controlling shades inside group? 
When I use remote to control somfy shades, all of them starts to move simultaneously, but when I use espsomfy groups, they starts moving one by one with slight delay

**Comment by AlexOwl** [comment]
Ok, I got it, you’ve implemented HA extension using cover groups, but why cant we just expose espsomfy group to HA as one separate device (one shade)? 
Another solution is to use some debounce algorithm

**Comment by rstrouse** [comment]
The up, down, and stop buttons should be instantaneous and operate as if they are a single motor in HASS.  In effect this is a single shade when these commands are issued because I have overridden the group functions that send these commands.  The positioning functions however, are at the mercy of HASS at this point unless I come up with a positioning algorithm in the firmware for unmatched group members.  Still there is about a 140ms per each command issued out of the radio so there will still be some delay between each command.   For instance, setting the lift position of the group to 30% will have some moving up and others moving down so each will need to be commanded separately.

The algorithm in the CoverGroup is not very good in my opinion.  I will see if I can do better, but there has been so much of the entity coding that I have had to work around.

**Comment by rstrouse** [comment]
This has been solid when opening and closing the group.  This does issue only one command to all motors when it is in a group.  However, it may issue several commands when the set position function is used in HA.  This is simply how groups work because each entity in the group could be already at different positions.  If you have any more questions about this feel free to re-open this issue.
